# Generated by Django 5.0.6 on 2024-06-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customers",
            new_name="Customer",
        ),
    ]
